University_Registration/Models/AdminModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace University_Registration.Models
{
    public class AdminModel
    {
        public string AdminName { get; set; }
        public string Password { get; set; }

    }
}

University_Registration/Models/LoginModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace University_Registration.Models
{
    public class LoginModel
    {
        public string AdminName { get; set; }
        public string Password { get; set; }

    }
}

University_Registration/Models/StudentModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace University_Registration.Models
{
    public class StudentModel
    {
        public int StudentId { get; set; } 
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public DateTime DOB { get; set; }
        public string GuardianName { get; set; }
        public string Email { get; set; }
        public string NID { get; set; }
        public string Status { get; set; }  
        public int TotalPoints { get; set; }
        public SubjectModel Subjects { get; set; }   


    }
}

University_Registration/Models/SubjectModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace University_Registration.Models
{
    public class SubjectModel
    {
        public int RecordID { get; set; }
        public int StdId { get; set; }
        public string Subject_1 { get; set; }
        public char Grade_1 { get; set; }
        public string Subject_2 { get; set; }
        public char Grade_2 { get; set; }
        public string Subject_3 { get; set; }
        public char Grade_3 { get; set; }
        public int Total { get; set; }

    }
}

University_Registration/Models/TempModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace University_Registration.Models
{
    public class TempModel
    {
        public StudentModel student { get; set; }
        public SubjectModel subject { get; set; }   
    }
}

University_Registration/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using University_Registration.BusinessLayer;
using University_Registration.Models;

namespace University_Registration.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            var waitingList = StudentBL.GetStudentWithConditions("Pending");
            var approvedList = StudentBL.GetStudentWithConditions("Approved");
            var rejectedList = StudentBL.GetStudentWithConditions("Rejected");
            ViewBag.WaitingList = waitingList;
            ViewBag.RejectedList = rejectedList;    
            ViewBag.ApprovedList = approvedList;
            return View();
        }
        public ActionResult Approve(int  id)
        {
            var result = StudentBL.ApproveStudent(id);
            if (result.Equals("Success"))
                return RedirectToAction("Index");

            return View();

        }
        public ActionResult Reject(int id)
        {
            var result = StudentBL.RejectStudent(id);
            if (result.Equals("Success"))
                return RedirectToAction("Index");

            return View();
        }
        public ActionResult MoveWait(int id)
        {
            var result = StudentBL.MoveToWaitingList(id);
            if (result.Equals("Success"))
                return RedirectToAction("Index");

            return View();
        }
        public void ExportCSV(string status)
        {
            StringWriter sw = new StringWriter();
            var studentsList = StudentBL.GetStudentWithConditions(status);

            sw.WriteLine("\"First Name\",\"Last Name\",\"DOB\",\"Email\",\"Total Points\"");

            Response.ClearContent();
            Response.AddHeader("content-disposition", "attachment;filename=Exported_Users.csv");
            Response.ContentType = "text/csv";

            foreach (var student in studentsList)
            {
                sw.WriteLine(string.Format("\"{0}\",\"{1}\",\"{2}\",\"{3}\",\"{4}\"",
                                           student.FirstName,
                                           student.Surname,
                                           student.DOB,
                                           student.Email,
                                           student.TotalPoints));
            }

            Response.Write(sw.ToString());
            Response.End();
        }
    }
}

University_Registration/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace University_Registration.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

University_Registration/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using University_Registration.BusinessLayer;
using University_Registration.Models;

namespace University_Registration.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Landing()
        {
            return View();
        }
        public JsonResult Authenticate(LoginModel loginModel)
        {
            var IsUserValid = AdminBL.AuthenticateUser(loginModel);
            if (IsUserValid)
            {
                this.Session["CurrentAdminName"] = loginModel.AdminName;
            }
            return Json(new { result = IsUserValid, url = Url.Action("Index", "Admin") });
        }
    }
}

University_Registration/Controllers/RegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using University_Registration.BusinessLayer;
using University_Registration.DataAccessLayer;
using University_Registration.Models;

namespace University_Registration.Controllers
{
    public class RegistrationController : Controller
    {
        // GET: Registration
        public ActionResult RegisterStudent()
        {
            return View();
        }

        [HttpPost]
        public JsonResult AddStudent(StudentModel student)
        {
            

            var IsUserValid = StudentBL.CheckUniqueStudent(student);
            if (IsUserValid)
            {
                //LoginModel employeeInfo = AppUserBL.GetEmployeeDetailsWithRoles(model);
                StudentBL.AddStudent(student);
                //get student ID
               student.Subjects.StdId = StudentBL.getStudentId(student);
                //input into Subject table with the student Id
                SubjectBL.AddSubjects(student.Subjects);

                //this.Session["CurrentUser"] = stdModel;
                this.Session["CurrentUser"] = student.FirstName;
            }
            return Json(new { result = IsUserValid, url = Url.Action("Index", "Home") });
        }

    }
}

University_Registration/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Welcome Admin: @Session["CurrentAdminName"] </h2>
<div class="jumbotron">
    <h2>Waiting List</h2>
    <p>@Html.ActionLink("Export to CSV", "ExportCSV", "Admin", new { status="Pending"}, null)</p>
    <table>
            <tr>
                <th>Student ID</th>
                <th>First Name</th>
                <th>Surname</th>
                <th>Email</th>
                <th>Status</th>
                <th>Total Points</th>
            </tr>

        <tbody>
            @foreach (var std in ViewBag.WaitingList)
            {
                <tr>
                    <td>@std.StudentId</td>
                    <td>@std.FirstName</td>
                    <td>@std.Surname</td>
                    <td>@std.Email</td>
                    <td>@std.Status</td>
                    <td>@std.TotalPoints</td>
                    <td>
                        @Html.ActionLink("Approve", "Approve", "Admin", new { id = std.StudentId }, null) |
                        @Html.ActionLink("Reject", "Reject", "Admin", new { id = std.StudentId }, null)
                    </td>
                </tr>
                <tr><td><hr/></td>  </tr>    
            }
        </tbody>
    </table>
    
</div>

<div class="jumbotron">
    <h2>Approved List</h2>
    <p>@Html.ActionLink("Export to CSV", "ExportCSV", "Admin", new { status = "Approved" }, null)</p>

    <table>
        <tr>
            <th>Student ID</th>
            <th>First Name</th>
            <th>Surname</th>
            <th>Email</th>
            <th>Status</th>
            <th>Total Points</th>
        </tr>
        <tbody>
            @foreach (var std in ViewBag.ApprovedList)
            {
                <tr>
                    <td>@std.StudentId</td>
                    <td>@std.FirstName</td>
                    <td>@std.Surname</td>
                    <td>@std.Status</td>
                    <td>@std.Email</td>
                    <td>@std.TotalPoints</td>
                    <td>
                        @Html.ActionLink("Move to Waiting List", "MoveWait", "Admin", new { id = std.StudentId }, null)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div class="jumbotron">
    <h2>Rejected List</h2>
    <p>@Html.ActionLink("Export to CSV", "ExportCSV", "Admin", new { status = "Rejected" }, null)</p>

    <table>
        <tr>
            <th>Student ID</th>
            <th>First Name</th>
            <th>Surname</th>
            <th>Email</th>
            <th>Status</th>
            <th>Total Points</th>
        </tr>
        <tbody>
            @foreach (var std in ViewBag.RejectedList)
            {
                <tr>
                    <td>@std.StudentId</td>
                    <td>@std.FirstName</td>
                    <td>@std.Surname</td>
                    <td>@std.Email</td>
                    <td>@std.Status</td>
                    <td>@std.TotalPoints</td>
                    <td>
                        @Html.ActionLink("Move to Waiting List", "MoveWait", "Admin", new { id = std.StudentId }, null)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

University_Registration/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

University_Registration/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

University_Registration/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>yoooooo</h1>
    <h1>@Session["CurrentUser"]</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

University_Registration/Views/Login/Landing.cshtml
@{
    ViewBag.Title = "Landing Page";
}

<h2>Landing Page</h2>
<p>Login</p>
<div class="registration-div">

    <form onsubmit="return loginValidation()">

        <label for="AdminName">Admin Name</label>
        <br />
        <input type="text" name="AdminName" value="" id="AdminName"/>
        <br />

        <label for="password">Password</label>
        <br />
        <input type="password" name="password" value="" id="Password" />
        <br />

        <input type="submit" name="loginBtn" value="Login" id="loginBtn" onclick="login()"/>

        <p>@Html.ActionLink("Register", "RegisterStudent", "Registration")</p>

    </form>

</div>

University_Registration/Views/Shared/_LandingPageLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script type="text/javascript" src="~/Scripts/script.js"></script>
    <script type="text/javascript" src="~/Scripts/login.js"></script>
    <script type="text/javascript" src="~/Scripts/loginValidation.js"></script>
    <script type="text/javascript" src="~/Scripts/registerValidation.js"></script>

    <script type="text/javascript" src="~/Scripts/login.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    @*https://codeseven.github.io/toastr/*@
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

University_Registration/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script type="text/javascript" src="~/Scripts/script.js"></script>
    <script type="text/javascript" src="~/Scripts/login.js"></script>

    <script type="text/javascript" src="~/Scripts/loginValidation.js"></script>
    <script type="text/javascript" src="~/Scripts/registerValidation.js"></script>

    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    @*https://codeseven.github.io/toastr/*@
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>